### ISSUE TITLE
docker compose v2

### ISSUE THREAD

**Issue by bytestream** [supportpal/helpdesk-install#32]
Issue to investigate what's necessary to support docker compose v2, https://docs.docker.com/compose/cli-command/

- [ ] Remove `docker-compose` dependency from docs

**Comment by bytestream** [comment]
@Gaitholabi if you have a spare min, could you give this a try? The two issues I mentioned in #74 might have been resolved now (according to the comments).

**Comment by Gaitholabi** [comment]
> @Gaitholabi if you have a spare min, could you give this a try? The two issues I mentioned in #74 might have been resolved now (according to the comments).

sure will do

**Comment by Gaitholabi** [comment]
> @Gaitholabi if you have a spare min, could you give this a try? The two issues I mentioned in #74 might have been resolved now (according to the comments).

Looks like it's resolved on `v2.2.1`

**Comment by bytestream** [comment]
I think docs.supportpal.com needs updating to replace `docker-compose` with `docker compose`, and the two setup scripts need to check for `docker compose`. For example, if I try to install monolithic using `setup.sh` at the moment it tells you to install docker compose. Dockers website has been updated to install v2 now. So you install v2 per the instructions but setup.sh continues to complain that `docker-compose` is missing and there's now no instructions on how to install `docker-compose` v1...
