### ISSUE TITLE
Running the Linux script again after an error

### ISSUE THREAD

**Issue by jshah4517** [supportpal/helpdesk-install#39]
If you run into an issue with the Linux script (such as what caused https://github.com/supportpal/helpdesk-install/pull/37), then trying to run it again will fail on potentially 3 points (could be more, but these are what I ran into):

- [ ]  Database already exists (have to uninstall MySQL with all databases)
- [ ]  Symlink of supportpal.conf already exists (remove file)
- [ ]  Cannot unlink 000-default.conf (have to re-create file)

Ideally, it should skip all these points if they exist or have already been removed.

**Comment by bytestream** [comment]
I think this needs an `--overwrite` option so the delete actions are explicitly defined.
